export default {
    EMAIL: "EMAIL",
    ACCESS_TOKEN: "ACCESS_TOKENT",
    JOURNALS: "JOURNALS",
    EXERCISES: "EXERCISES",
    SUMMARY: "SUMMARY",
    ADVICE: "ADVICE",
    ASSETS: "ASSETS",
    LIABILITIES: "LIABILITIES",
    PROFILE: "PROFILE",
    LOGOUT: "LOGOUT"
}