export default {
    EMAIL: "EMAIL",
    ACCESS_TOKEN: "ACCESS_TOKENT",
    JOURNALS: "JOURNALS",
    EXERCISES: "EXERCISES",
    SUMMARY: "SUMMARY",
    ADVICE: "ADVICE",
    ASSETS: "ASSETS",
    LIABILITIES: "LIABILITIES",
    PROFILE: "PROFILE",
    LOGOUT: "LOGOUT",
    GOALS: "GOALS",
    ADD_GOALS: "ADD_GOALS",
    REMOVE_GOALS: "REMOVE_GOALS",
    REMOVE_UPDATE_GOALS: "REMOVE_UPDATE_GOALS",
    UPDATE_GOAL_DETAILS: "UPDATE_GOAL_DETAILS",
    ACCOUNTS: "ACCOUNTS"
}